### PR TITLE
updated Readme, added Adafruit Feather M0 Express

### PR DESCRIPTION
**Pull request by armsp**
I had opened issue #66 and after finally figuring out the issue with some assistance I was able to get it working with Adafruit Feather M0 Express. Eventually I closed the issue.   
This fork and the subsequent pull request addresses the changes I had to make - specifically adding the vendor id and product id to the list and some instructions in the Readme to help novices like me find their way around - to get it working.
Do have a look. The changes are minimal and nothing will break. Feel free to edit or request edits from me.

### CODE REVIEW

**Comment by ladyada** [comment]
@reillyeon why do you do any filtering on the VID/PID?

**Comment by armsp** [comment]
@ladyada the `vendorId` and `productId` of Feather M0 Basic would be the same or different? If it's the same then I can add that too. Please let me know.

**Comment by ladyada** [comment]
ideally there'd be no filter at all- there's hundreds of boards that could use this example site, why make it harder? :)

**Comment by armsp** [comment]
@ladyada i concur. Perhaps @reillyeon could expound on why he decided to settle with filters.

**Comment by reillyeon** [comment]
Filtering devices is recommended to reduce end-user confusion by presenting the user with only the devices that are supported by the site. If no filters are provided then the user will have to choose between every USB device on their system.

**Comment by armsp** [comment]
Ohh...thanks a lot for the explanation @reillyeon !.

**Comment by ladyada** [comment]
@reillyeon can you wildcard the PID? like anything with the adafruit 0x239a VID is approved? we release new hardware every week, it will be very hard to keep that up.

**Comment by reillyeon** [comment]
> @reillyeon can you wildcard the PID? like anything with the adafruit 0x239a VID is approved? we release new hardware every week, it will be very hard to keep that up.

Yes, a filter containing only a vendor ID is valid. `{ 'vendorId': 0x239A }` would match all Adafruit devices.

This library individually added Arduino devices to the filter because only some of them were supported.

**Comment by ladyada** [comment]
PR submitted :)

**Pull request merged**
